# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [8]:
import numpy as np

arr1 = np.full((5,5), 6)
arrFill = np.zeros((3,3))
arr1[1:-1,1:-1] = arrFill
arr1

array([[6, 6, 6, 6, 6],
       [6, 0, 0, 0, 6],
       [6, 0, 0, 0, 6],
       [6, 0, 0, 0, 6],
       [6, 6, 6, 6, 6]])

Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [29]:
import numpy as np

arr = np.full((8,8),3)
arr[::2,1::2] = 9
arr[1::2,0::2] = 9
arr

array([[3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3]])

Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [31]:
import numpy as np

arrEmpty = np.empty((3,4))
print(arrEmpty)
arrFull = np.full((3,3), 6)
print(arrFull)

[[ 1.49166815e-154 -1.29074384e-231  3.95252517e-323  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Fahrenheit
degrees into the Centigrade degrees and the Fahrenheit values are
stored in the NumPy array.
    
    Sample Array -[ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [35]:
import numpy as np

fahrenheit = np.array([0, 12, 45.21 ,34, 99.91])
centigrade = (fahrenheit - 32)/1.8 
centigrade

array([-17.77777778, -11.11111111,   7.33888889,   1.11111111,
        37.72777778])

Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [40]:
import numpy as np

arr = np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
print('Real part of the array -', arr.real)
print('Imaginary part of the array -', arr.imag)

Real part of the array - [1.         0.70710678]
Imaginary part of the array - [0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [45]:
import numpy as np

arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array(([0, 40]))

np.in1d(arr1,arr2)

array([ True, False, False,  True, False])

Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [46]:
import numpy as np

arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array(([10, 30, 40]))

arr1[np.in1d(arr1,arr2)]

array([10, 40])

Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [52]:
import numpy as np

arr1 = np.array([10, 10, 20, 20, 30, 30])
print(f'unique elements of {arr1} are {np.unique(arr1)}')
arr2 = [[1, 1], [2, 3]]
print(f'unique elements of {arr2} are {np.unique(arr2)}')

unique elements of [10 10 20 20 30 30] are [10 20 30]
unique elements of [[1, 1], [2, 3]] are [1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [53]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])
np.setxor1d(array1, array2)

array([ 0, 20, 30, 50, 60, 70, 80])

Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [55]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60, 80])
print(np.all(array1))
array2 = np.array([1,1])
print(np.all(array2))

False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [60]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60, 80])
print(np.any(array1))
array2 = np.array([0,0])
print(np.all(array2))

True
False


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [64]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
print(f'Repeating {arr1} 2 times {np.tile(arr1, 2)}')
print(f'Repeating {arr1} 2 times {np.tile(arr1, 3)}')

Repeating [1 2 3 4] 2 times [1 2 3 4 1 2 3 4]
Repeating [1 2 3 4] 2 times [1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [68]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6])
print('Maximum value index -', arr1.argmax())
print('Minumum value index -', arr1.argmin())

Maximum value index - 5
Minumum value index - 0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [69]:
import numpy as np
a = np.array([1, 2])
b = np.array([4, 5])
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)

[False False]
[False False]
[ True  True]
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [79]:
import numpy as np

arr = np.array([[4, 6],[2, 1]])
print(np.sort(arr, axis = 0))
print(np.sort(np.sort(arr, axis = 0), axis = 1))



[[2 1]
 [4 6]]
[[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [86]:
import numpy as np

firstNames = np.array(( 'Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery' ))
lastNames = np.array(( 'Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum' ))
np.lexsort((lastNames, firstNames))


array([0, 3, 2, 4, 1])

Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [89]:
import numpy as np

arr = np.array([[0, 10, 20], [20, 30, 40]])
print('Values bigger than 10 =', arr[np.where(arr>10)])
print('Their indices are', np.where(arr>10))

Values bigger than 10 = [20 20 30 40]
Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [97]:
import numpy as np

arr = np.array([[0, 10, 20], [20, 30, 40]])

print(f'Number of elements in arr is {arr.size}, size of each element is {arr.itemsize} and array size is {arr.size*arr.itemsize}')

Number of elements in arr is 6, size of each element is 8 and array size is 48


## Great Job!